selectors=[
"body :empty",
"div:not(.example)",
"p:contains(selectors)",
"div p a",
"div, p, a",
"div p",
"body div",
".note",
"ul.toc li.tocline2",
"ul.toc > li.tocline2",
"tr .pattern",
"p",
"div",
"div ~ p",
"div > div",
"div ~ div",
"div > p",
"body",
"div + p",
"div ~ p",
"div[class^=exa][class$=mple]",
"div.example",
"ul .tocline2",
"div.example, div.note",
"#title",
"h1#title",
"div#title",
"h1#title + div > p",
"a[href][lang][class]",
"div[class]",
"div[class=example]",
"div[class^=exa]",
"div[class$=mple]",
"div[class*=e]",
"div[class|=dialog]",
"div[class!=made_up]",
"div[class~=example]",
"p:nth-child(even)",
"p:nth-child(2n)",
"p:nth-child(odd)",
"p:nth-child(2n+1)",
"p:nth-child(n)",
"p:only-child",
"p:last-child",
"p:first-child",
"div :only-child",
"div :only-of-type",
"th:first-of-type",
"th:last-of-type",
"td:nth-of-type(even)",
"td:nth-last-of-type(odd)"
//"td:odd",
//"p:even"
]
